import { ResponsiveTable } from '../../components/data/ResponsiveDataView';
import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Search, ShieldCheck, Users } from 'lucide-react';
import { platformApi } from '../../api/platform';
import Pagination from '../../components/data/Pagination';
import { useDebouncedValue } from '../../hooks/useDebouncedValue';

interface EmployeeRow { id: string; employeeId: string; name: string; email?: string; companyId?: { _id: string; name: string; companyCode: string }; department?: string; designation?: string; employmentType?: string; status: string; joiningDate?: string }
interface CompanyOption { _id: string; name: string; companyCode: string }

export default function PlatformEmployeesPage() {
  const [search, setSearch] = useState(''); const [companyId, setCompanyId] = useState(''); const [status, setStatus] = useState('ALL'); const [page, setPage] = useState(1);
  const debounced = useDebouncedValue(search, 350);
  const query = useQuery({ queryKey: ['platform', 'employees', debounced, companyId, status, page], queryFn: () => platformApi.getEmployees<{ employees: EmployeeRow[]; companies: CompanyOption[]; pagination: { total: number; page: number; limit: number; totalPages: number }; privacy: string }>({ search: debounced || undefined, companyId: companyId || undefined, status, page, limit: 25 }).then((response) => response.data) });
  return <div className="admin-page"><header className="admin-page__header"><div><h1>Platform employee directory</h1><p>Private platform-operations visibility across tenants. Companies cannot see this page or know when it is used.</p></div><span className="health-chip"><ShieldCheck size={15} />Restricted Super Admin view</span></header>
    <section className="admin-card employee-privacy-note"><Users size={18} /><div><strong>Minimum necessary employee data</strong><p>{query.data?.privacy ?? 'Salary, banking, documents and identity data are excluded from this cross-tenant directory.'}</p></div></section>
    <section className="admin-card platform-employee-filters"><label><Search size={15} /><input aria-label="Search employees" placeholder="Name, ID, email or designation" value={search} onChange={(event) => { setSearch(event.target.value); setPage(1); }} /></label><select aria-label="Filter by company" value={companyId} onChange={(event) => { setCompanyId(event.target.value); setPage(1); }}><option value="">All companies</option>{query.data?.companies.map((company) => <option key={company._id} value={company._id}>{company.name} · {company.companyCode}</option>)}</select><select aria-label="Filter by status" value={status} onChange={(event) => { setStatus(event.target.value); setPage(1); }}><option value="ALL">All statuses</option>{['Invited', 'Onboarding', 'Active', 'Inactive', 'NoticePeriod', 'Terminated', 'Archived'].map((item) => <option key={item}>{item}</option>)}</select></section>
    <section className="admin-card" style={{ overflowX: 'auto' }}><ResponsiveTable className="org-table"><thead><tr><th>Employee</th><th>Company</th><th>Department</th><th>Designation</th><th>Employment</th><th>Status</th><th>Joined</th></tr></thead><tbody>{query.data?.employees.map((employee) => <tr key={employee.id}><td><strong>{employee.name}</strong><small style={{ display: 'block', color: '#64748b' }}>{employee.employeeId}{employee.email ? ` · ${employee.email}` : ''}</small></td><td>{employee.companyId?.name ?? '—'}<small style={{ display: 'block', color: '#64748b' }}>{employee.companyId?.companyCode}</small></td><td>{employee.department ?? '—'}</td><td>{employee.designation ?? '—'}</td><td>{employee.employmentType ?? '—'}</td><td><span className={`admin-status ${employee.status === 'Active' ? 'success' : 'neutral'}`}>{employee.status}</span></td><td>{employee.joiningDate ? new Date(employee.joiningDate).toLocaleDateString('en-IN') : '—'}</td></tr>)}</tbody></ResponsiveTable>{!query.isLoading && !query.data?.employees.length && <div className="empty-state"><Users size={24} /><strong>No matching employees</strong></div>}</section>
    {query.data && <Pagination page={page} totalPages={query.data.pagination.totalPages} total={query.data.pagination.total} limit={query.data.pagination.limit} onPageChange={setPage} />}</div>;
}
