import { useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { KeyRound, Search, ShieldCheck, UserX } from 'lucide-react';
import { toast } from 'sonner';
import { platformApi } from '../../api/platform';

export default function UsersAccessPage() {
  const client = useQueryClient(); const [search, setSearch] = useState(''); const [role, setRole] = useState('ALL');
  const query = useQuery({ queryKey: ['platform', 'users', search, role], queryFn: () => platformApi.getUsers<any>({ search: search || undefined, role }).then((response) => response.data) });
  const reason = (action: string) => window.prompt(`Reason for ${action}:`)?.trim();
  const revoke = async (user: any) => { const why = reason(`revoking ${user.name}'s sessions`); if (!why) return; await platformApi.revokeUserSessions(user.id, why); toast.success('Sessions revoked.'); await client.invalidateQueries({ queryKey: ['platform', 'users'] }); };
  const toggle = async (user: any) => { const why = reason(`${user.isActive ? 'suspending' : 'reactivating'} ${user.name}`); if (!why) return; await platformApi.updateUser(user.id, { isActive: !user.isActive, reason: why }); toast.success('Access updated.'); await client.invalidateQueries({ queryKey: ['platform', 'users'] }); };
  return <div className="admin-page"><header className="admin-page__header"><div><h1>Users & access</h1><p>Review platform identities, primary roles, scoped assignments, login state, and active sessions.</p></div><div className="health-chip"><ShieldCheck size={15} /> Privileged changes audited</div></header><section className="admin-card" style={{ padding: 16 }}><div style={{ display: 'flex', gap: 10, flexWrap: 'wrap' }}><label className="admin-search"><Search size={15} /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search name or email" /></label><select className="admin-input" style={{ maxWidth: 190 }} value={role} onChange={(e) => setRole(e.target.value)}>{['ALL','SUPER_ADMIN','COMPANY_ADMIN','HR','MANAGER','SUPERVISOR','FINANCE','EMPLOYEE'].map((item) => <option key={item}>{item}</option>)}</select></div></section><section className="admin-card" style={{ overflow: 'auto' }}><table className="org-table"><thead><tr><th>User</th><th>Company</th><th>Primary role</th><th>Scoped roles</th><th>Sessions</th><th>Last login</th><th /></tr></thead><tbody>{query.data?.map((user) => <tr key={user.id}><td><strong>{user.name}</strong><small style={{ display: 'block', color: '#64748b' }}>{user.email}</small></td><td>{user.companyId?.name ?? 'Platform'}</td><td><span data-status={user.isActive ? 'ACTIVE' : 'SUSPENDED'}>{user.role}</span>{user.role === 'SUPER_ADMIN' && <small style={{ display: 'block' }}>2FA {user.twoFactorEnabled ? 'enabled' : 'pending'}</small>}</td><td>{user.assignments?.map((item: any) => `${item.role} · ${item.scopeType}`).join(', ') || '—'}</td><td>{user.activeSessions}</td><td>{user.lastLoginAt ? new Date(user.lastLoginAt).toLocaleString('en-IN') : 'Never'}</td><td><button className="icon-button" title="Revoke sessions" onClick={() => void revoke(user)}><KeyRound size={15} /></button><button className="icon-button" title={user.isActive ? 'Suspend access' : 'Reactivate access'} onClick={() => void toggle(user)}><UserX size={15} /></button></td></tr>)}</tbody></table></section></div>;
}
