import { useEffect, useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Fingerprint, LocateFixed, PlugZap, ScanFace, ShieldCheck } from 'lucide-react';
import { toast } from 'sonner';
import { organizationApi } from '../../api/organization';

interface Manifest { key: string; name: string; mode: string; description: string; fields: readonly string[] }
interface Connection { id: string; providerKey: string; displayName: string; connectionMode: string; status: string; publicConfig: Record<string, unknown>; deviceSerials: string[]; secretConfigured: boolean; lastTestedAt?: string }
interface Policy { verificationMethods?: Record<string, boolean>; requireAnyVerification?: boolean; minimumGpsAccuracyMeters?: number; allowRemoteAttendance?: boolean }

const methodInfo = [
  { key: 'gps', label: 'Capture GPS', detail: 'Record employee coordinates and device accuracy.', icon: LocateFixed },
  { key: 'geofence', label: 'Enforce branch geofence', detail: 'Accept mobile punches only inside an active branch radius.', icon: ShieldCheck },
  { key: 'device', label: 'Registered device', detail: 'Accept attendance events from activated terminals only.', icon: Fingerprint },
  { key: 'face', label: 'Face verification', detail: 'Require a verified face event from an activated provider.', icon: ScanFace },
  { key: 'biometric', label: 'Fingerprint / biometric', detail: 'Require a biometric event from an activated connection.', icon: Fingerprint },
];
const EMPTY_MANIFESTS: Manifest[] = [];

export default function CAAttendanceIntegrationsPage() {
  const client = useQueryClient();
  const query = useQuery({ queryKey: ['ca', 'attendance-integrations'], queryFn: () => organizationApi.getAttendanceIntegrations<{ manifests: Manifest[]; connections: Connection[]; policy: Policy }>().then((response) => response.data) });
  const manifests = query.data?.manifests ?? EMPTY_MANIFESTS;
  const connections = query.data?.connections ?? [];
  const [policy, setPolicy] = useState<Policy>({ verificationMethods: {}, requireAnyVerification: true, minimumGpsAccuracyMeters: 100, allowRemoteAttendance: false });
  const [form, setForm] = useState({ providerKey: 'MOBILE_GEOLOCATION', displayName: 'Primary attendance connection', baseUrl: '', bridgeId: '', callbackKey: '', deviceSerials: '', apiSecret: '' });
  useEffect(() => { if (query.data?.policy) setPolicy((current) => ({ ...current, ...query.data!.policy, verificationMethods: { ...current.verificationMethods, ...query.data!.policy.verificationMethods } })); }, [query.data]);
  useEffect(() => { if (manifests.length && !manifests.some((manifest) => manifest.key === form.providerKey)) setForm((current) => ({ ...current, providerKey: manifests[0]!.key })); }, [manifests, form.providerKey]);
  const selected = useMemo(() => manifests.find((manifest) => manifest.key === form.providerKey), [manifests, form.providerKey]);
  const refresh = () => client.invalidateQueries({ queryKey: ['ca', 'attendance-integrations'] });
  const saveConnection = useMutation({ mutationFn: () => organizationApi.saveAttendanceIntegration({ providerKey: form.providerKey, displayName: form.displayName, publicConfig: { baseUrl: form.baseUrl || undefined, bridgeId: form.bridgeId || undefined, callbackKey: form.callbackKey || undefined }, deviceSerials: form.deviceSerials.split(',').map((item) => item.trim()).filter(Boolean), secrets: form.apiSecret ? { apiSecret: form.apiSecret } : {}, reason: 'Company attendance connection configuration' }), onSuccess: () => { toast.success('Attendance connection saved as draft.'); void refresh(); }, onError: (error: any) => toast.error(error.response?.data?.message ?? 'Unable to save connection.') });
  const savePolicy = useMutation({ mutationFn: () => organizationApi.saveAttendancePolicy({ ...policy, reason: 'Company attendance verification policy' }), onSuccess: () => { toast.success('Attendance verification policy saved.'); void refresh(); } });
  const connectionAction = async (connection: Connection, action: 'test' | 'activate') => { try { await organizationApi.attendanceIntegrationAction(connection.id, action); toast.success(action === 'test' ? 'Configuration test passed.' : 'Attendance connection activated.'); await refresh(); } catch (error: any) { toast.error(error.response?.data?.message ?? `Unable to ${action} connection.`); } };

  return <div className="admin-page">
    <header className="admin-page__header"><div><h1>Attendance integrations</h1><p>Configure this company’s fingerprint, face, biometric API and GPS attendance. Credentials and devices remain isolated to this tenant.</p></div><span className="health-chip"><PlugZap size={15} />{connections.filter((item) => item.status === 'ACTIVE').length} active</span></header>

    <section className="admin-card attendance-policy-card"><header><div><h2>Verification policy</h2><p>Choose the evidence required for employee attendance. Branch coordinates and radius are managed under Organization.</p></div></header><div className="verification-method-grid">{methodInfo.map(({ key, label, detail, icon: Icon }) => { const enabled = Boolean(policy.verificationMethods?.[key]); return <button type="button" aria-pressed={enabled} className={enabled ? 'is-enabled' : ''} key={key} onClick={() => setPolicy((current) => ({ ...current, verificationMethods: { ...current.verificationMethods, [key]: !enabled } }))}><Icon size={18} /><span><strong>{label}</strong><small>{detail}</small></span>{enabled && <ShieldCheck size={15} />}</button>; })}</div><div className="policy-controls"><label className="admin-label">Minimum GPS accuracy (metres)<input className="admin-input" type="number" min={5} max={500} value={policy.minimumGpsAccuracyMeters ?? 100} onChange={(event) => setPolicy({ ...policy, minimumGpsAccuracyMeters: Number(event.target.value) })} /></label><label className="policy-check"><input type="checkbox" checked={policy.requireAnyVerification !== false} onChange={(event) => setPolicy({ ...policy, requireAnyVerification: event.target.checked })} /> Require configured verification for self attendance</label><label className="policy-check"><input type="checkbox" checked={Boolean(policy.allowRemoteAttendance)} onChange={(event) => setPolicy({ ...policy, allowRemoteAttendance: event.target.checked })} /> Allow attendance outside a branch geofence</label><button className="admin-button" disabled={savePolicy.isPending} onClick={() => savePolicy.mutate()}>{savePolicy.isPending ? 'Saving…' : 'Save policy'}</button></div></section>

    <section className="admin-card attendance-connection-builder"><header><div><h2>Add attendance connection</h2><p>Choose the vendor or verification channel used by this company.</p></div></header><div className="form-grid"><label className="admin-label">Provider<select className="admin-input" value={form.providerKey} onChange={(event) => setForm({ ...form, providerKey: event.target.value })}>{manifests.map((manifest) => <option key={manifest.key} value={manifest.key}>{manifest.name}</option>)}</select></label><label className="admin-label">Connection name<input className="admin-input" value={form.displayName} onChange={(event) => setForm({ ...form, displayName: event.target.value })} /></label>{selected?.fields.includes('baseUrl') && <label className="admin-label">Secure API URL<input className="admin-input" type="url" placeholder="https://provider.example/api" value={form.baseUrl} onChange={(event) => setForm({ ...form, baseUrl: event.target.value })} /></label>}{selected?.fields.includes('bridgeId') && <label className="admin-label">Local bridge ID<input className="admin-input" value={form.bridgeId} onChange={(event) => setForm({ ...form, bridgeId: event.target.value })} /></label>}{selected?.fields.includes('callbackKey') && <label className="admin-label">Callback key<input className="admin-input" value={form.callbackKey} onChange={(event) => setForm({ ...form, callbackKey: event.target.value })} /></label>}<label className="admin-label">Device serials (comma separated)<input className="admin-input" value={form.deviceSerials} onChange={(event) => setForm({ ...form, deviceSerials: event.target.value })} /></label><label className="admin-label">API secret / token<input className="admin-input" type="password" value={form.apiSecret} onChange={(event) => setForm({ ...form, apiSecret: event.target.value })} /></label></div><div className="builder-note"><strong>{selected?.name}</strong><span>{selected?.description}</span><small>Connection mode: {selected?.mode?.replaceAll('_', ' ')}</small></div><footer><button className="admin-button" disabled={saveConnection.isPending || !selected} onClick={() => saveConnection.mutate()}>{saveConnection.isPending ? 'Saving…' : 'Save connection draft'}</button></footer></section>

    <section><h2 className="section-title">Configured connections <span>({connections.length})</span></h2><div className="attendance-connection-grid">{connections.map((connection) => <article className="admin-card" key={connection.id}><header><div className="provider-icon"><PlugZap size={17} /></div><div><strong>{connection.displayName}</strong><small>{connection.providerKey.replaceAll('_', ' ')} · {connection.connectionMode.replaceAll('_', ' ')}</small></div><span className={`admin-status ${connection.status === 'ACTIVE' ? 'success' : connection.status === 'ERROR' ? 'danger' : 'neutral'}`}>{connection.status}</span></header><p>{connection.deviceSerials?.length ? `${connection.deviceSerials.length} registered devices` : 'No device serial restriction'}</p><footer><button className="admin-button admin-button--secondary" onClick={() => void connectionAction(connection, 'test')}>Test configuration</button><button className="admin-button" disabled={connection.status !== 'TESTED'} onClick={() => void connectionAction(connection, 'activate')}>Activate</button></footer></article>)}</div></section>
  </div>;
}
